### ISSUE TITLE
Fix Terraform issues with v1.1.x

### ISSUE THREAD

**Issue by dariush-a** [GCPartner/terraform-gcpartner-anthos-baremetal#2]
Hi all,
@c0dyhi11 
Terraform version used v1.1.7
When running the terraform on a baremetal cloud env, I get the following error:

```
│ Error: file provisioner error
│ 
│   with module.PNAP_Infra[0].null_resource.node_networking_cp[1],
│   on modules/phoenixnap/main.tf line 87, in resource "null_resource" "node_networking_cp":
│   87:   provisioner "file" {
│ 
│ Upload failed: scp: $HOME/bootstrap: No such file or directory

```

Reproduction steps:

1. create a terraform.tfvars file with the required parameters (including client id/secret)
2. gcloud auth application-default login
3. terraform init, plan, apply creates the control plane and worker nodes but fails to complete the deployment with the error shown above.

![Screenshot 2022-03-28 19 51 24](https://user-images.githubusercontent.com/102377306/160524541-3af4baf9-2d47-463c-b3ed-262f1652ac13.png)

![Screenshot 2022-03-28 19 54 54](https://user-images.githubusercontent.com/102377306/160524580-d9ad2f50-2db2-4737-a191-0199865ff2c7.png)

**Comment by c0dyhi11** [comment]
This issue only shows up with Terraform newer than `v1.0.x` We need to make this repo work with the latest version of terraform.

**Comment by masrur** [comment]
[destination](https://www.terraform.io/language/resources/provisioners/file#destination) - (Required) This is the destination path. It must be specified as an absolute path.

https://www.terraform.io/language/resources/provisioners/file#:~:text=destination%20%2D%20(Required)%20This%20is%20the%20destination%20path.%20It%20must%20be%20specified%20as%20an%20absolute%20path.
