### ISSUE TITLE
Documentation: Setting up ENV

### ISSUE THREAD

**Issue by c0dyhi11** [GCPartner/terraform-gcpartner-anthos-baremetal#4]
Pre-Reqs:
GCloud Installed locally
Terraform installed Locally
Anything else we didn't think of.

**Comment by dariush-a** [comment]
Terraform version must be < 1.0.11
Deployment still continues after an hour. Need to break it and manually do the rest of setup.
![image](https://user-images.githubusercontent.com/102377306/162063378-a0c4c0bc-3390-4a29-8eac-1b79d390e52c.png)
